version: '2'
services:
  sidotv1-app:
    image: sidotv1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sidotv1-mssql:1433;database=SidotV1
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  sidotv1-mssql:
    extends:
      file: mssql.yml
      service: sidotv1-mssql
